starting log for step: prepare
context: 
 {'readwrite': [u'/Users/lukas/Code/yadagedev/yadage/examples/testflows/mcprodflowsub/work1'], 'readonly': [], 'metadir': '/Users/lukas/Code/yadagedev/yadage/examples/testflows/mcprodflowsub/work1/_packtivity'}

--------------
run in docker container: lukasheinrich/higgs-mc-studies
with env: default env
command: ./paramfromyaml.py --madgraph HC_UFO -i "{kHzz: 0.1, kAzz: 0.1, kHww: 0.3, kAww: 0.3}" /Users/lukas/Code/yadagedev/yadage/examples/testflows/mcprodflowsub/work1/param.dat
resources: []
--------------
    
dogrid: False do_cvmfs: False
docker run  command: 
docker run --rm -v /Users/lukas/Code/yadagedev/yadage/examples/testflows/mcprodflowsub/work1:/Users/lukas/Code/yadagedev/yadage/examples/testflows/mcprodflowsub/work1:rw --cidfile /Users/lukas/Code/yadagedev/yadage/examples/testflows/mcprodflowsub/work1/_packtivity/prepare.cid lukasheinrich/higgs-mc-studies sh -c ' ./paramfromyaml.py --madgraph HC_UFO -i "{kHzz: 0.1, kAzz: 0.1, kHww: 0.3, kAww: 0.3}" /Users/lukas/Code/yadagedev/yadage/examples/testflows/mcprodflowsub/work1/param.dat'
started run subprocess with pid 47500. now wait to finish
process children: []
Unexpected error: (<type 'exceptions.KeyboardInterrupt'>, KeyboardInterrupt(), <traceback object at 0x1085dc170>)
Traceback (most recent call last):
  File "/Users/lukas/Code/yadagedev/packtivity/packtivity/handlers/environment_handlers.py", line 123, in docker_run
    proc.communicate()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 795, in communicate
    self.wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1375, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
finally for run
prepare raised exception
Traceback (most recent call last):
  File "/Users/lukas/Code/yadagedev/packtivity/packtivity/__init__.py", line 27, in packtivity
    run_in_env(uniquetag,step['environment'],job,context)
  File "/Users/lukas/Code/yadagedev/packtivity/packtivity/__init__.py", line 21, in run_in_env
    return handler(nametag,environment,context,command)
  File "/Users/lukas/Code/yadagedev/packtivity/packtivity/handlers/environment_handlers.py", line 162, in docker_enc_handler
    docker_run(docker_run_cmd,log,context,nametag)
  File "/Users/lukas/Code/yadagedev/packtivity/packtivity/handlers/environment_handlers.py", line 123, in docker_run
    proc.communicate()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 795, in communicate
    self.wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1375, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
